#!/bin/bash

eclipse(){
SSLPASS="$(cat ${DEVOPS_SRC_PATH}/auth/.ssl_pass)"
PASSWORD="$(cat ${DEVOPS_SRC_PATH}/auth/.password | openssl enc -aes-256-cbc -a -d -salt -pass pass:$SSLPASS)"
sudo -b -p $PASSWORD -u mateus ~/eclipse/eclipse
}

# Variáveis das cores utilizadas no output.
COLOR_DEFAULT='\033[0m'
COLOR_GRAY='\033[2m'
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[0;33m'
COLOR_BLUE='\033[0;34m'
COLOR_WHITE='\033[0;37m'
COLOR_BOLD_WHITE='\033[1;37m'


# CHECK_SYMBOL
# ==========================================
#
# Ícone check ✔ com cor verde.
CHECK_SYMBOL="${COLOR_GREEN}\u2714${COLOR_DEFAULT}"

# ERROR_SYMBOL
# ==========================================
#
# Ícone de erro ✖ com cor vermelha.
ERROR_SYMBOL="${COLOR_RED}\u2716${COLOR_DEFAULT}"


# Variáveis utilizadas para remover indentação
# no output dos métodos.
# TODO: Fortes candidatos a serem deletados.

# 1 Tab
indent1x='
  '

# 2 Tabs
indent2x='
    '

# 3 Tabs
indent3x='
      '

# 4 Tabs
indent4x='
        '

# 5 Tabs
indent5x='
          '
