#!/bin/bash

clear-memory () {
  sudo sync; echo 'echo 1 > /proc/sys/vm/drop_caches' | sudo sh
  sudo sync; echo 'echo 2 > /proc/sys/vm/drop_caches' | sudo sh
  sudo sync; echo 'echo 3 > /proc/sys/vm/drop_caches' | sudo sh
}
